### ISSUE TITLE
Bugfix for image encoder

### ISSUE THREAD

**Issue by ItsGers8** [4Guys1Game/croaker#41]
- [ ] Het TO en FO en andere beroepsdocumenten zijn bijgewerkt
- [ ] De individuele projectverslagen / logboek zijn bijgewerkt
- [ ] De code is getest volgens het testplan en bevat geen fouten meer
- [ ] De Scrum documentatie (burndown chart, backlogs) is up-to-date
- [ ] De code is voorzien van passend commentaar

**Comment by jaschutte** [comment]
Fixed long ago
